### ISSUE TITLE
TypeError: Cannot read property 'containerId' of undefined

### ISSUE THREAD

**Issue by Mercuryinhell** [google/ga4-gtm-migration#1]
Tried to do an event migration today and got this error. Not sure how to fix it.
It will run through 2 tags and add them, but then stop with the error.

**Comment by b-kuehn** [comment]
Thanks for reporting an issue. Could you describe what exactly you were doing in the sheet when you encountered this error and perhaps share a screenshot of the issue?

**Comment by Mercuryinhell** [comment]
I was at the final step "Migrate Event Tags" and the script runs and then produces the error.
![ga4 migration error](https://user-images.githubusercontent.com/60720149/183735897-dcbdfea5-dbe8-47b1-b4b2-2bb35ff3b53b.PNG)

**Comment by Mercuryinhell** [comment]
To bypass that error, I grabbed the container id and hard coded it, and then it failed on this error: TypeError: Cannot read property 'name' of undefined

**Comment by b-kuehn** [comment]
The new tag isn't being created for some reason so things like "name" and "containerId" don't exist when the new tag is being referenced. The issue with creating the new tag should be logged in the "executions" area in the Apps Script connected to the sheet.

**Comment by Mercuryinhell** [comment]
Sorry, I don't know much about scripting here. but here is what I got from "migrateEventTag"
2:55:32 PM	Error	
TypeError: Cannot read property 'oldTag' of undefined
migrateEventTag	@ utils/migration.gs:184

And from from "migrateEventTags"

2:55:55 PM	Notice	Execution started
2:56:30 PM	Info	{ [GoogleJsonResponseException: API call to tagmanager.accounts.containers.workspaces.tags.create failed with error: vendorTemplate.parameter.eventParameters[1].name: Parameter names cannot start with _
vendorTemplate.parameter.eventParameters[2].name: Parameter names cannot start with _
]
  name: 'GoogleJsonResponseException',
  details: 
   { errors: [ [Object] ],
     message: 'vendorTemplate.parameter.eventParameters[1].name: Parameter names cannot start with _\nvendorTemplate.parameter.eventParameters[2].name: Parameter names cannot start with _\n',
     code: 400 } }
     
2:56:32 PM	Error	
TypeError: Cannot read property 'name' of undefined
migrateEventTag	@ utils/migration.gs:251
(anonymous)	@ utils/migration.gs:171
migrateEventTags	@ utils/migration.gs:170

![script error 2](https://user-images.githubusercontent.com/60720149/183739473-90c1d03a-1099-4e90-adef-75dbf010e0e5.PNG)

**Comment by b-kuehn** [comment]
The issue you're running into is that parameter names cannot start with an underscore. If you change your parameter names so that they don't start with "_" and rerun the script, then it should work.

**Comment by Mercuryinhell** [comment]
I noticed that and looked at the params and didn't find any like that. I do however think I determined the issue. The user had added to columns M > S new parameters in addition to the conversion from cat/act/lbl. I think moving those to col U > AB as net new might have solved the issue. Update: that did not fix it.

**Comment by Mercuryinhell** [comment]
Ok, I figured it out. I had to inspect all fields and 2 of them were like this as parameter names:
"ua_event_category
"
"ua_event_action
"
Looks like that new line will break it.

**Comment by b-kuehn** [comment]
Sounds good. Glad you were able to identify the issue.
